import type { Product } from '@gemcart/core';

export type Gender = 'men' | 'women' | 'kids' | 'unisex';
export type Category = 'tops' | 'dresses' | 'shoes' | 'trousers' | 'jewellery' | 'activewear' | 'swimwear' | 'lingerie' | 'beauty' | 'bags' | 'outerwear' | 'traditional';

export type CatalogProduct = Product & {
  gender: Gender;
  category: Category;
  imageUrl: string;
};

// Note: Using source.unsplash.com category queries (royalty-free demo). Images rotate but remain valid.
export const catalog: CatalogProduct[] = [
  {
    id: 'm-top-tee-1',
    slug: 'mens-classic-tee',
    name: 'Mens Classic Tee',
    description: 'Soft crew neck cotton tee',
    priceNGN: 850000,
    images: [],
    tags: ['tee','tops'],
    sizes: ['S','M','L','XL'],
    colors: ['black','white','green'],
    inStock: true,
    gender: 'men',
    category: 'tops',
    imageUrl: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-top-hoodie-1',
    slug: 'lagos-street-hoodie',
    name: 'Lagos Street Hoodie',
    description: 'Cozy fleece hoodie for cool nights',
    priceNGN: 1950000,
    images: [],
    tags: ['hoodie','tops'],
    sizes: ['M','L','XL'],
    colors: ['black','grey'],
    inStock: true,
    gender: 'men',
    category: 'tops',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-trouser-1',
    slug: 'tech-flex-joggers',
    name: 'Tech Flex Joggers',
    description: 'Stretch joggers with zip pockets',
    priceNGN: 1450000,
    images: [],
    tags: ['joggers','trousers'],
    sizes: ['S','M','L','XL'],
    colors: ['black','navy'],
    inStock: true,
    gender: 'men',
    category: 'trousers',
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-shoes-1',
    slug: 'naija-runner-sneakers',
    name: 'Naija Runner Sneakers',
    description: 'Lightweight everyday sneakers',
    priceNGN: 2350000,
    images: [],
    tags: ['sneakers','shoes'],
    sizes: ['41','42','43','44'],
    colors: ['white','black'],
    inStock: true,
    gender: 'men',
    category: 'shoes',
    imageUrl: 'https://via.placeholder.com/900x900/4b0f7b/e3c268?text=Naija+Runner+Sneakers',
  },
  {
    id: 'w-top-tee-1',
    slug: 'naija-heritage-tee',
    name: 'Naija Heritage Tee',
    description: 'Relaxed fit tee with heritage print',
    priceNGN: 920000,
    images: [],
    tags: ['tee','tops'],
    sizes: ['XS','S','M','L'],
    colors: ['white','green','black'],
    inStock: true,
    gender: 'women',
    category: 'tops',
    imageUrl: 'https://via.placeholder.com/900x900/4b0f7b/e3c268?text=Heritage+Tee',
  },
  {
    id: 'w-dress-1',
    slug: 'ankara-fusion-dress',
    name: 'Ankara Fusion Dress',
    description: 'Modern silhouette with Ankara accents',
    priceNGN: 2850000,
    images: [],
    tags: ['dress','ankara'],
    sizes: ['S','M','L'],
    colors: ['multi'],
    inStock: true,
    gender: 'women',
    category: 'dresses',
    imageUrl: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'w-shoes-1',
    slug: 'elevate-heels',
    name: 'Elevate Heels',
    description: 'Elegant heels for nights out',
    priceNGN: 1750000,
    images: [],
    tags: ['heels','shoes'],
    sizes: ['37','38','39','40'],
    colors: ['black','nude'],
    inStock: true,
    gender: 'women',
    category: 'shoes',
    imageUrl: 'https://via.placeholder.com/900x900/4b0f7b/e3c268?text=Zuka+Fashion',
  },
  {
    id: 'w-trouser-1',
    slug: 'high-rise-tailored-trousers',
    name: 'High-Rise Tailored Trousers',
    description: 'Sharp cut with comfortable stretch',
    priceNGN: 1680000,
    images: [],
    tags: ['trousers','tailored'],
    sizes: ['S','M','L'],
    colors: ['black','khaki'],
    inStock: true,
    gender: 'women',
    category: 'trousers',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'jewel-1',
    slug: 'adire-bead-necklace',
    name: 'Adire Bead Necklace',
    description: 'Hand-inspired beaded necklace',
    priceNGN: 480000,
    images: [],
    tags: ['jewellery','necklace'],
    sizes: [],
    colors: ['multi'],
    inStock: true,
    gender: 'women',
    category: 'jewellery',
    imageUrl: 'https://images.unsplash.com/photo-1522312298940-653d2b79dbb5?auto=format&fit=crop&w=900&q=80',
  },
  // Activewear
  {
    id: 'w-active-1',
    slug: 'naija-gym-set',
    name: 'Naija Gym Set',
    description: 'Sports bra and leggings combo',
    priceNGN: 1250000,
    images: [],
    tags: ['activewear','gym'],
    sizes: ['XS','S','M','L'],
    colors: ['black','green'],
    inStock: true,
    gender: 'women',
    category: 'activewear',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-active-1',
    slug: 'mens-track-jacket',
    name: 'Men\'s Track Jacket',
    description: 'Athletic track jacket with Nigerian colors',
    priceNGN: 1850000,
    images: [],
    tags: ['activewear','jacket'],
    sizes: ['M','L','XL','XXL'],
    colors: ['green','white'],
    inStock: true,
    gender: 'men',
    category: 'activewear',
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
  },
  // Swimwear
  {
    id: 'w-swim-1',
    slug: 'beach-vibes-bikini',
    name: 'Beach Vibes Bikini',
    description: 'Two-piece swimsuit with print',
    priceNGN: 980000,
    images: [],
    tags: ['swimwear','beach'],
    sizes: ['S','M','L'],
    colors: ['multi','green'],
    inStock: true,
    gender: 'women',
    category: 'swimwear',
    imageUrl: 'https://via.placeholder.com/900x900/4b0f7b/e3c268?text=Zuka+Fashion',
  },
  // Bags & Accessories
  {
    id: 'w-bag-1',
    slug: 'lagos-tote-bag',
    name: 'Lagos Tote Bag',
    description: 'Spacious leather tote perfect for everyday',
    priceNGN: 1450000,
    images: [],
    tags: ['bags','tote'],
    sizes: [],
    colors: ['brown','black'],
    inStock: true,
    gender: 'women',
    category: 'bags',
    imageUrl: 'https://images.unsplash.com/photo-1522312298940-653d2b79dbb5?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'w-bag-2',
    slug: 'crossbody-mini',
    name: 'Crossbody Mini Bag',
    description: 'Compact crossbody for essentials',
    priceNGN: 850000,
    images: [],
    tags: ['bags','crossbody'],
    sizes: [],
    colors: ['black','gold'],
    inStock: true,
    gender: 'women',
    category: 'bags',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  // Traditional Wear
  {
    id: 'w-trad-1',
    slug: 'ankara-maxi-dress',
    name: 'Ankara Maxi Dress',
    description: 'Flowing maxi with authentic Ankara print',
    priceNGN: 3200000,
    images: [],
    tags: ['traditional','ankara'],
    sizes: ['S','M','L','XL'],
    colors: ['multi'],
    inStock: true,
    gender: 'women',
    category: 'traditional',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-trad-1',
    slug: 'agbada-set',
    name: 'Classic Agbada Set',
    description: 'Traditional Agbada with embroidery',
    priceNGN: 4500000,
    images: [],
    tags: ['traditional','agbada'],
    sizes: ['M','L','XL'],
    colors: ['white','gold'],
    inStock: true,
    gender: 'men',
    category: 'traditional',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
  },
  // Outerwear
  {
    id: 'w-outer-1',
    slug: 'bomber-jacket-gold',
    name: 'Gold Trim Bomber',
    description: 'Satin bomber with gold accents',
    priceNGN: 2150000,
    images: [],
    tags: ['outerwear','jacket'],
    sizes: ['S','M','L'],
    colors: ['black','green'],
    inStock: true,
    gender: 'women',
    category: 'outerwear',
    imageUrl: 'https://images.unsplash.com/photo-1519744792095-2f2205e87b6f?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'm-outer-1',
    slug: 'denim-jacket',
    name: 'Distressed Denim Jacket',
    description: 'Classic denim with modern fit',
    priceNGN: 1950000,
    images: [],
    tags: ['outerwear','denim'],
    sizes: ['M','L','XL'],
    colors: ['blue','black'],
    inStock: true,
    gender: 'men',
    category: 'outerwear',
    imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
  },
  // Beauty
  {
    id: 'beauty-1',
    slug: 'glow-serum',
    name: 'Nigerian Glow Serum',
    description: 'Natural ingredients for radiant skin',
    priceNGN: 680000,
    images: [],
    tags: ['beauty','skincare'],
    sizes: ['30ml'],
    colors: [],
    inStock: true,
    gender: 'unisex',
    category: 'beauty',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'beauty-2',
    slug: 'matte-lipstick-set',
    name: 'Matte Lipstick Collection',
    description: 'Set of 5 vibrant shades',
    priceNGN: 950000,
    images: [],
    tags: ['beauty','makeup'],
    sizes: [],
    colors: ['multi'],
    inStock: true,
    gender: 'women',
    category: 'beauty',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80',
  },
  // Kids
  {
    id: 'kids-1',
    slug: 'kids-ankara-dress',
    name: 'Girls Ankara Dress',
    description: 'Cute dress with traditional prints',
    priceNGN: 780000,
    images: [],
    tags: ['kids','dress'],
    sizes: ['2-3Y','4-5Y','6-7Y'],
    colors: ['multi'],
    inStock: true,
    gender: 'kids',
    category: 'dresses',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'kids-2',
    slug: 'boys-shorts-set',
    name: 'Boys Casual Set',
    description: 'T-shirt and shorts combo',
    priceNGN: 650000,
    images: [],
    tags: ['kids','casual'],
    sizes: ['2-3Y','4-5Y','6-7Y','8-9Y'],
    colors: ['green','white'],
    inStock: true,
    gender: 'kids',
    category: 'tops',
    imageUrl: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=900&q=80',
  },
];

export function listProducts(gender?: Gender, category?: Category): CatalogProduct[] {
  return catalog.filter(p => (!gender || p.gender === gender) && (!category || p.category === category));
}

export function getBySlug(slug: string): CatalogProduct | undefined {
  return catalog.find(p => p.slug === slug);
}


